[package]
name = "lrzhs_ffi"
version = "0.1.0"
authors = [
    "Jack Grigg <jack@z.cash>",
    "Francisco Gindre <francisco@z.cash>",
    "Kris Nuttycombe <kris@nutty.land>",
]
license = "MIT"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0"
ffi_helpers = "0.3"
zcash_address = "0.10"
zcash_protocol = "0.7"
orchard = { version = "0.14", default-features = false }
zip32 = "0.2"

[build-dependencies]
cbindgen = "0.27"

[lib]
name = "lrzhs_ffi"
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
